# Copyright 2025 OpenPE Contributors — Licensed under GPL-3.0
# Modified by Maxen Wong, 2026

"""Report generator for OpenPE Phase 6.

Collects artifacts from all phases and assembles a structured
REPORT.md following the OpenPE report format.

Reference: OpenPE spec Section 3.2 Phase 6
"""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from datetime import datetime

import yaml


@dataclass
class ReportSection:
    """A section of the report."""
    title: str
    content: str
    level: int = 2  # heading level


@dataclass
class ReportBuilder:
    """Builds the OpenPE analysis report from phase artifacts."""
    analysis_name: str
    question: str = ""
    sections: list[ReportSection] = field(default_factory=list)

    def add_section(self, title: str, content: str, level: int = 2) -> None:
        self.sections.append(ReportSection(title=title, content=content, level=level))

    def collect_from_phases(self, analysis_dir: Path) -> None:
        """Collect content from phase artifacts."""
        # Phase 0: Discovery
        discovery = self._read_artifact(analysis_dir / "phase0_discovery" / "exec" / "DISCOVERY.md")
        if discovery:
            self.add_section("First Principles Identified", discovery)

        data_quality = self._read_artifact(analysis_dir / "phase0_discovery" / "exec" / "DATA_QUALITY.md")
        if data_quality:
            self.add_section("Data Foundation", data_quality)

        # Phase 1: Strategy
        strategy = self._read_artifact(analysis_dir / "phase1_strategy" / "exec" / "STRATEGY.md")
        if strategy:
            self.add_section("Analysis Strategy", strategy)

        # Phase 3: Analysis
        analysis = self._read_artifact(analysis_dir / "phase3_analysis" / "exec" / "ANALYSIS.md")
        if analysis:
            self.add_section("Analysis Findings", analysis)

        # Phase 4: Projection
        projection = self._read_artifact(analysis_dir / "phase4_projection" / "exec" / "PROJECTION.md")
        if projection:
            self.add_section("Forward Projection", projection)

        # Phase 5: Verification
        verification = self._read_artifact(analysis_dir / "phase5_verification" / "exec" / "VERIFICATION.md")
        if verification:
            self.add_section("Verification Results", verification)

    def _read_artifact(self, path: Path) -> str | None:
        """Read an artifact file, return None if not found."""
        if path.exists():
            return path.read_text().strip()
        return None

    def build_executive_summary(self, summary_text: str = "") -> str:
        """Generate executive summary placeholder or provided text."""
        if summary_text:
            return summary_text
        return (
            "> **Note:** This executive summary should be written by the report_writer agent "
            "based on the complete analysis findings below.\n\n"
            f"Analysis of: {self.question}\n"
        )

    def render(self) -> str:
        """Render the complete report as Markdown."""
        lines = [
            f"# {self.analysis_name}",
            "",
            f"*Generated: {datetime.now().strftime('%Y-%m-%d')}*",
            "",
            "## Executive Summary",
            "",
            self.build_executive_summary(),
            "",
        ]

        for i, section in enumerate(self.sections, 1):
            prefix = "#" * section.level
            lines.extend([
                f"{prefix} {i}. {section.title}",
                "",
                section.content,
                "",
            ])

        # Appendix
        lines.extend([
            "## Appendix",
            "",
            "### A. Data Provenance",
            "",
            "> See `phase0_discovery/data/registry.yaml` for full data provenance.",
            "",
            "### B. Code References",
            "",
            "> Analysis scripts are in `phase3_analysis/scripts/`.",
            "> Projection scripts are in `phase4_projection/scripts/`.",
            "",
            "---",
            f"*Report generated by OpenPE v0.1.0*",
        ])

        return "\n".join(lines)

    def save(self, output_path: Path) -> Path:
        """Render and save the report."""
        content = self.render()
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(content)
        return output_path

    def collect_figures(self, analysis_dir: Path) -> list[Path]:
        """Collect all PDF figures from phase figure directories.

        Returns list of PDF paths sorted by phase then name.
        Skips PNG (PDF is preferred for pandoc/LaTeX).
        """
        analysis_dir = Path(analysis_dir)
        figures = []
        for phase_dir in sorted(analysis_dir.glob("phase*")):
            fig_dir = phase_dir / "figures"
            if fig_dir.exists():
                for pdf in sorted(fig_dir.glob("*.pdf")):
                    figures.append(pdf)
        return figures

    def to_dict(self) -> dict:
        return {
            "analysis_name": self.analysis_name,
            "question": self.question,
            "sections": [{"title": s.title, "level": s.level} for s in self.sections],
            "generated": datetime.now().isoformat(),
        }
